### ISSUE TITLE
Thoughts, process, submissions, etc.

### ISSUE THREAD

**Issue by gingerbeardman** [ace-dent/8x8.me#4]
Feel free to move this to a Discussion

I'm happy to submit my pattern collection.

- ~~Will have to dig for old screens, because they have been decomposed into just the 8x8 patterns, with no references as to where they came from.~~
  I decided to capture most of them again as I had kept all the apps installed.

- I have a script that sorts them by brightness, and I keep only those with brightness between 128 and 255, as the lower half of the range can be filled with inverted patterns.

- I store them as pgm text based image format, which makes processing them easier and makes removing duplicates much easier as there is no need to deal with differences in image compression, colour depth, etc.

![159_04](https://github.com/ace-dent/8x8.me/assets/49612/80ed8f49-50ae-4c50-9f44-4fffef051bd5)

159_04.pgm
```
P2
8 8
255
0 0 255 255 255 255 255 0 
0 255 255 255 255 255 0 0 
255 255 255 255 255 0 0 0 
255 255 255 255 0 0 0 255 
255 255 255 0 0 0 255 255 
255 255 0 0 0 255 255 255 
255 0 0 0 255 255 255 255 
0 0 0 255 255 255 255 255 
```

- I'm still figuring out a way to deal with patterns that are the same but offset. Maybe there's a rule that can be introduced to unify the offset?

- I use [Piskel](https://blog.gingerbeardman.com/2023/05/10/piskel-for-playdate/) to split an image/screengrab into tiles, at which point it can save them as a handy zip. Let me know if you want more info!

**Comment by ace-dent** [comment]
Hi. Just a quick reply to say 'Thank You'! 
Really appreciate your effort on this... I will draft a longer reply that sets out the project's policy on how we draw _inspiration_ from these works but cannot directly copy bitmaps. (It should be in `contributing.md`). 
I'm looking forward to reviewing all these wonderful screen shots you've shared. It was exactly the early Mac software that motivated me; I've tried to trace some patterns back to Bill Atkinson (/Mark Cutter) and then the refined work of Susan Kare.

Like `pgm`, this project uses the sibling format `pbm` as a human-readable, archival format. Equivalent example [here](https://github.com/ace-dent/8x8.me/blob/main/04-Lines/pbm/SinisterSparseBold.pbm).

**Comment by gingerbeardman** [comment]
The policy outline you briefly mention has me a bit worried TBH. But let's see what it says.

I don't know why I chose pgm, as pbm would simplify things a little more for me. I'll switch to that too.

**Comment by gingerbeardman** [comment]
Any news on the policy outline? This alone will dictate whether I remain involved. 

I mean I've already given away my collection, you live and learn, but how they'll be used is key to my involvement/time.

**Comment by ace-dent** [comment]
Hi @gingerbeardman. 
Thanks for your patience. Your contributions are gratefully received, but did raise some issues.
Entirely on me- I hadn't really documented / communicated well for external contributors.

In short: It is important this project remains CC0/ Public Domain, so all works must be original or sufficiently transformative works. Therefore, this project doesn't seek to be an Archive (where archive.org is better placed), but instead draws *inspiration* from historic pixel art. I have spent many hours this week looking at legislation and best practice. It may still take longer until I have a formal policy drafted on that. I also want to prepare the project more generally, for receiving a broader community. Thank you again for catalysing this effort.

Amongst the patterns you shared, there are certainly some 'classics' from which I hope to draw inspiration to expand the current collection. These are likely to be transformed not copied, and as always, drawn from a blank canvas. You will be acknowledged on any commits. Many of the vintage patterns (or equivalents) already exist in the collection, so I have started to note these too. 

> I've already given away my collection

I don't want you to feel you have lost anything! Your ideas, contributions and comments are very welcome... and I feel we have a shared love for this art form! But I completely understand if you would prefer to withdraw your collection. I hope we can find a solution that is satisfactory. 
All the best,
A

**Comment by gingerbeardman** [comment]
OK, well, I guess this is lesson learned for both of us.

Had I have know this beforehand I would not have shared my collection with you. 

Your original tweet: 
> Hi 👋 ~ I'm trying to archive many 'classic' patterns... would you be able to dump those screenshots somewhere?  :-D

I feel this was grossly misleading, as there was never any plan to archive them.

Finally, personally I don't why there's a need to avoid the original patterns given that many programs from vendors large and small used the exact same patterns with no issues, and much art was created with them that could be a source for the patterns. So I'm sorry to say that in that case your project doesn't align with my goals.

And with that, I'm out. Best of luck to you and no hard feelings.

**Comment by ace-dent** [comment]
Hi. 
Thanks for your reply.
I'm so sorry for any misunderstanding! My comment on Twitter was re. my personal collection (I also nerd out and keep similar screenshots! 🤓). Perhaps I should have been more clear in my message. 
It was a pleasant surprise when you started sharing to this project but not something I anticipated.
I regret that I haven't had better Docs in place to explain the intent and restrictions for this project. This is something I hope to fix.

I appreciate the time and effort you made in raising issues and sharing images. Thank you. To improve, I would like to understand better your disappointment; are you looking for a bit-accurate archive of these images? Are you concerned about attribution? ...or anything else? If you have time to explain your frustration(s), I'd humbly welcome the feedback.

> I don't why there's a need to avoid the original patterns

It's a tricky legal issue and I'm certainly erring on the side of caution! You may well be correct. My hope is that the most people possible can use this work, for the widest variety of projects, so a very permissive license is essential. In providing that license, I need to do so in good-faith. I think if you also browse the current galleries, you will see many of these classic patterns represented. 

> Best of luck to you and no hard feelings.

Thank you again. All the best!
