### ISSUE TITLE
Sharing for Playdate SDK

### ISSUE THREAD

**Issue by gingerbeardman** [ace-dent/8x8.me#5]
The most succinct format is 0x hex representation as mentioned in the docs.

But I use a more obvious and "readable" binary specification, as follows:

```lua
-- binary string to number
local function b(e)
    return tonumber(e, 2)
end

pattern = {	--  diagonal lines
    b('11110000'),
    b('11100001'),
    b('11000011'),
    b('10000111'),
    b('00001111'),
    b('00011110'),
    b('00111100'),
    b('01111000'),
}
```

**Comment by ace-dent** [comment]
Currently the project supports `Pulp` but not Playdate's Lua SDK[^1]. I'd be happy to draft something for feedback...?
I would prefer hex to binary numbers if they're not natively supported, and use visual comment lines as per the other code formats.

[^1]: I didn't realise there was built-in support for this! 😅

**Comment by gingerbeardman** [comment]
No worries, in that case the code you generate will be most similar to Thumby, just with a Lua flavour to the definitions.

https://sdk.play.date/inside-playdate/#f-graphics.setPattern

**Comment by gingerbeardman** [comment]
Thumby
```py
bayerDither08 = bytearray([
    # BITMAP: width: 8, height: 8, [85,170,85,170,85,170,85,170]
    0x55,  # ▓░▓░▓░▓░
    0xAA,  # ░▓░▓░▓░▓
    0x55,  # ▓░▓░▓░▓░
    0xAA,  # ░▓░▓░▓░▓
    0x55,  # ▓░▓░▓░▓░
    0xAA,  # ░▓░▓░▓░▓
    0x55,  # ▓░▓░▓░▓░
    0xAA,  # ░▓░▓░▓░▓
])
# bayerDither08Sprite = thumby.Sprite(8, 8, bayerDither08)
```

Lua
```lua
bayerDither08 = {
    -- BITMAP: width: 8, height: 8, [85,170,85,170,85,170,85,170]
    0x55,  -- ▓░▓░▓░▓░
    0xAA,  -- ░▓░▓░▓░▓
    0x55,  -- ▓░▓░▓░▓░
    0xAA,  -- ░▓░▓░▓░▓
    0x55,  -- ▓░▓░▓░▓░
    0xAA,  -- ░▓░▓░▓░▓
    0x55,  -- ▓░▓░▓░▓░
    0xAA,  -- ░▓░▓░▓░▓
}
-- playdate.graphics.setPattern(bayerDither08)
```

**Comment by gingerbeardman** [comment]
The only other thing to mention is that Playdate SDK setPattern() accepts an extra 8 rows of values that describe the alpha mask. In my WIP pattern library, I can specify:

1. the normal pattern, opaque
2. the normal pattern, with alpha (white as transparent)
3. the inverted pattern, opaque
4. the inverted pattern, with alpha (white as transparent)

Because the default Playdate SDK's setDitherPattern() sets the built-in patterns (mostly Bayer, and a few types of lines) with opacity, my main use of custom patterns is also with opacity. 

Opacity allows "stacking" or "overdraw" of patterns to achieve even fancier patterns, or simply to allow you to see one thing behind the other in your game. 

But the option is there for opaque, which is what you'd mostly want if using these as tiles in Pulp, etc. 

This might complicate things!

**Comment by ace-dent** [comment]
Hi @gingerbeardman ,

Looked over the specs and thinking something like this:

```lua
-- header
local gfx <const> = playdate.graphics

local skullXL <const> = {
    0x00,  -- ▓▓▓▓▓▓▓▓
    0x7C,  -- ▓░░░░░▓▓
    0xFE,  -- ░░░░░░░▓
    0xFE,  -- ░░░░░░░▓
    0x92,  -- ░▓▓░▓▓░▓
    0xEE,  -- ░░░▓░░░▓
    0x7C,  -- ▓░░░░░▓▓
    0x54,  -- ▓░▓░▓░▓▓
}
-- gfx.setPattern(skullXL)
```

I think `gfx` shorthand seems preferred in practice?... or might this confuse newcomers to the SDK / issues with copy-pasting code?
Would welcome your feedback :-)

<hr>

> setPattern() accepts an extra 8 rows of values that describe the alpha mask

I don't plan on supporting masking (just opaque patterns).

**Comment by gingerbeardman** [comment]
Supporting only opaque patterns will make this largely of little use to SDK developers. At least it would in my experience.

Better would be to only support alpha patterns as that is what would be needed the majority of the time and would follow the lead of the SDK itself. 

A compromise could be to add a comment on how the developer can modify the pattern definition to make it alpha in the expected way. (I'd have to check if it is just simple duplication of the rows or if they need to be inverted.)

> The default SDK dither pattern generator generates only alpha patterns. It's the most common and versatile use. I guess for other platforms you are supporting the major/only use is for opaque tiles? SDK uses patterns for much more than that.
> 
> Imagine it like painting and being able to mix "colours" (or not in the case of opaque patterns). 
> 
> Plus, with only alpha patterns the developer can choose to draw them onto a colour and make them opaque if they need to (though it's rare). But it's *much* more difficult to draw an opaque pattern with alpha after the fact. 

---- 

`gfx.` is a personal preference which I think should be left to the individual rather than forced here.

----

Here are two of my games whose graphics were drawn using only shapes and alpha patterns. There are no bitmap images loaded in either game, and no opaque patterns used. 

> If only opaque patterns were available I never would have considered this approach because of the additional code/effort/overhead involved. 

![image](https://cdn.gingerbeardman.com/images/posts/ball-und-panzer-golf-05.gif)

![image](https://github.com/ace-dent/8x8.me/assets/49612/c672a9c4-2c07-4440-9a7f-e1ac90ff6e47)

**Comment by ace-dent** [comment]
> A compromise could be to add a comment

Thanks for this valuable feedback. Would something like this work for you?

```lua
local skullXL <const> = {
    0x00,  -- ▓▓▓▓▓▓▓▓
    0x7C,  -- ▓░░░░░▓▓
    0xFE,  -- ░░░░░░░▓
    0xFE,  -- ░░░░░░░▓
    0x92,  -- ░▓▓░▓▓░▓
    0xEE,  -- ░░░▓░░░▓
    0x7C,  -- ▓░░░░░▓▓
    0x54,  -- ▓░▓░▓░▓▓
    -- 0,124,254,254,146,238,124,84, -- transparent background 
    -- 255,131,1,1,109,17,131,171, -- transparent foreground 
}
```
(I may have them the wrong way around- so please test...).

**Comment by ace-dent** [comment]
Hi @gingerbeardman - reopening, as I will add this in due course (also awaiting feedback from others). Cheers.

**Comment by ace-dent** [comment]
Complete. First patterns now [added](https://github.com/ace-dent/8x8.me/blob/main/15-Other/README.md) (more will follow).
Thanks again.
